import os
import uuid
import subprocess
import threading
import json
import shutil
import tempfile
from flask import Flask, request, jsonify, send_file, render_template_string
from pathlib import Path

app = Flask(__name__)

UPLOAD_DIR = Path(tempfile.gettempdir()) / "k3nna_uploads"
OUTPUT_DIR = Path(tempfile.gettempdir()) / "k3nna_outputs"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

jobs = {}
jobs_lock = threading.Lock()


def get_python_path():
    for p in ["python3", "python"]:
        path = shutil.which(p)
        if path:
            return path
    return "python3"


def run_conversion(job_id, file_path, options):
    python = get_python_path()
    file_path = Path(file_path)
    output_dir = OUTPUT_DIR / job_id
    output_dir.mkdir(parents=True, exist_ok=True)
    build_dir = output_dir / "build"

    args = [python, "-m", "PyInstaller"]

    if options.get("oneFile", True):
        args.append("--onefile")

    if options.get("windowed", True):
        args.append("--windowed")

    if options.get("stripBinaries", False):
        args.append("--strip")

    if options.get("optimize", False):
        args.append("--optimize=2")

    custom = options.get("customOptions", "").strip()
    if custom:
        args.extend(custom.split())

    args.extend([
        "--clean",
        "--distpath", str(output_dir / "dist"),
        "--workpath", str(build_dir),
        "--specpath", str(output_dir),
        str(file_path)
    ])

    with jobs_lock:
        jobs[job_id]["status"] = "running"
        jobs[job_id]["progress"] = 10
        jobs[job_id]["log"] = "[1/3] Preparing environment...\n"

    try:
        proc = subprocess.Popen(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            cwd=str(file_path.parent)
        )

        log_lines = []
        for line in proc.stdout:
            log_lines.append(line)
            with jobs_lock:
                jobs[job_id]["log"] = "".join(log_lines)
                cur = jobs[job_id].get("progress", 10)
                if cur < 85:
                    jobs[job_id]["progress"] = min(cur + 1, 85)

        proc.wait()

        if proc.returncode != 0:
            with jobs_lock:
                jobs[job_id]["status"] = "failed"
                jobs[job_id]["progress"] = 0
                jobs[job_id]["error"] = "PyInstaller exited with code " + str(proc.returncode)
            return

        dist_dir = output_dir / "dist"
        executables = list(dist_dir.glob("*")) if dist_dir.exists() else []

        if not executables:
            with jobs_lock:
                jobs[job_id]["status"] = "failed"
                jobs[job_id]["progress"] = 0
                jobs[job_id]["error"] = "No output produced by PyInstaller"
            return

        exe_path = executables[0]

        script_content = None
        if options.get("createScript", True):
            fname = file_path.stem
            icon_arg = ""
            if options.get("iconPath"):
                icon_arg = f"    --icon={options['iconPath']} \\\n"
            script_content = f"""#!/bin/bash
# Automated build script for {fname}
# Generated by K3nna Python to Executable Converter

set -e

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

echo "========================================"
echo "  K3NNA - Python Compiler"
echo "  Building: {fname}"
echo "========================================"

if ! command -v python3 &> /dev/null; then
    echo -e "${{RED}}✗ Error: Python 3 is not installed${{NC}}"
    exit 1
fi
echo -e "${{GREEN}}✓ Python 3 found${{NC}}"

if ! python3 -m pip show pyinstaller &> /dev/null; then
    echo -e "${{YELLOW}}⚠ PyInstaller not found. Installing...${{NC}}"
    python3 -m pip install pyinstaller
fi
echo -e "${{GREEN}}✓ PyInstaller ready${{NC}}"

OUTPUT_DIR="{fname}_exe"
mkdir -p "$OUTPUT_DIR"

python3 -m PyInstaller \\
    --onefile \\
    --windowed \\
    --clean \\
{icon_arg}    --distpath "$OUTPUT_DIR" \\
    --buildpath build \\
    --specpath . \\
    {fname}.py

rm -rf build
rm -f {fname}.spec

echo -e "${{GREEN}}✓ Build complete!${{NC}}"
echo "========================================"
"""

        with jobs_lock:
            jobs[job_id]["status"] = "done"
            jobs[job_id]["progress"] = 100
            jobs[job_id]["exe_name"] = exe_path.name
            jobs[job_id]["exe_path"] = str(exe_path)
            jobs[job_id]["script"] = script_content
            jobs[job_id]["log"] += "\n✓ Conversion complete!\n"

        shutil.rmtree(build_dir, ignore_errors=True)
        spec_file = output_dir / (file_path.stem + ".spec")
        spec_file.unlink(missing_ok=True)

    except Exception as e:
        with jobs_lock:
            jobs[job_id]["status"] = "failed"
            jobs[job_id]["progress"] = 0
            jobs[job_id]["error"] = str(e)


@app.route("/")
def index():
    with open("templates/index.html") as f:
        return f.read()


@app.route("/api/convert", methods=["POST"])
def convert():
    if "file" not in request.files:
        return jsonify({"error": "No file provided"}), 400

    f = request.files["file"]
    if not f.filename.endswith(".py"):
        return jsonify({"error": "Only .py files are accepted"}), 400

    options = {}
    if "options" in request.form:
        try:
            options = json.loads(request.form["options"])
        except Exception:
            pass

    job_id = str(uuid.uuid4())
    job_dir = UPLOAD_DIR / job_id
    job_dir.mkdir(parents=True, exist_ok=True)
    file_path = job_dir / f.filename
    f.save(str(file_path))

    with jobs_lock:
        jobs[job_id] = {
            "status": "queued",
            "progress": 0,
            "log": "",
            "filename": f.filename,
            "exe_name": None,
            "exe_path": None,
            "script": None,
            "error": None,
        }

    t = threading.Thread(target=run_conversion, args=(job_id, file_path, options), daemon=True)
    t.start()

    return jsonify({"jobId": job_id})


@app.route("/api/status/<job_id>")
def status(job_id):
    with jobs_lock:
        job = jobs.get(job_id)
    if not job:
        return jsonify({"error": "Job not found"}), 404
    return jsonify(job)


@app.route("/api/download/<job_id>")
def download(job_id):
    with jobs_lock:
        job = jobs.get(job_id)
    if not job or job["status"] != "done":
        return jsonify({"error": "Not ready"}), 404
    exe_path = job["exe_path"]
    if not exe_path or not Path(exe_path).exists():
        return jsonify({"error": "File not found"}), 404
    return send_file(exe_path, as_attachment=True, download_name=job["exe_name"])


@app.route("/api/download-script/<job_id>")
def download_script(job_id):
    with jobs_lock:
        job = jobs.get(job_id)
    if not job or job["status"] != "done":
        return jsonify({"error": "Not ready"}), 404
    script = job.get("script")
    if not script:
        return jsonify({"error": "No script available"}), 404
    fname = Path(job["filename"]).stem
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".sh", delete=False)
    tmp.write(script)
    tmp.close()
    return send_file(tmp.name, as_attachment=True, download_name=f"build_{fname}.sh")


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False)
